import { OnInit } from "@angular/core";
import { ConnectionsService } from "../shared/services/connectionsService";
import { SalesforceoAuthService } from "../shared/services/salesforceoAuth";
import { WindowRef } from "../shared/services/windowRefService";
import { ModalDirective } from "ng2-bootstrap";
import { Router } from "@angular/router";
import { ConnectionsFieldDetailService } from "./connections.connectionsdetails.service";
import { ConnectionsListComponent } from "./connections-list.component";
export declare class AddNewConnectionComponent implements OnInit {
    private connectionService;
    private salesforceoAuthService;
    private _window;
    private _connectionFieldDetailService;
    private _router;
    private _ConnectionListComponent;
    isSalesForceConnection: boolean;
    addNewConnectionModal: ModalDirective;
    newConnectionsListModal: ModalDirective;
    activeConnectionsExist: boolean;
    private connectionsConfigURL;
    private postConnectionsURL;
    private oAuthURL;
    private clientID;
    private callbackUrl;
    private _popUpWindow;
    private basicConnectionObj;
    newConnectionsObj: any;
    private userName;
    connectionDescription: string;
    connectionCategory: string;
    private addConnectionFields;
    private inputData;
    private loadingRedirectURL;
    className: string;
    colorByConnectionType: string;
    connectionDisplayString: string;
    connectorTitle: string;
    private loginSavebuttonCaption;
    private redirectQueryParam;
    baseLocationhRef: string;
    constructor(connectionService: ConnectionsService, salesforceoAuthService: SalesforceoAuthService, _window: WindowRef, _connectionFieldDetailService: ConnectionsFieldDetailService, _router: Router, _ConnectionListComponent: ConnectionsListComponent);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    addNewConnection(settings: any, category: any): boolean;
    closeAddNewConnection(): void;
    closeNewConnectionsListModal(): void;
    getClassNameByConnectionType(connectionType: any): string;
    getConnectorIconSrc(category: any): string;
}
