import { OnInit } from "@angular/core";
import { ConnectionsService } from "../shared/services/connectionsService";
import { SalesforceoAuthService } from "../shared/services/salesforceoAuth";
import { MarketooAuthService } from "../shared/services/marketooAuth";
import { BasicConnection } from "../../common/models/connector";
import { WindowRef } from "../shared/services/windowRefService";
import { ModalDirective } from "ng2-bootstrap";
import { Router, ActivatedRoute } from "@angular/router";
export declare class AddEditConnectionDetailsComponent implements OnInit {
    private connectionService;
    private salesforceoAuthService;
    private marketooAuthService;
    private _window;
    private _router;
    private _activatedRoute;
    connectorObj: {};
    addEditConnectionDetail: ModalDirective;
    connectionsConfigURL: string;
    postConnectionsURL: string;
    oAuthURL: string;
    clientID: string;
    callbackUrl: string;
    _popUpWindow: any;
    basicConnectionObj: BasicConnection;
    newConnectionsObj: any;
    connectionCategory: string;
    addConnectionFields: any;
    connectionDetailsInputFields: Array<{}>;
    inputData: {};
    loadingRedirectURL: boolean;
    className: string;
    colorByConnectionType: string;
    connectionDisplayString: string;
    loginSavebuttonCaption: string;
    redirectQueryParam: string;
    editMode: boolean;
    userName: string;
    connectionDescription: string;
    api_version: string;
    marketoClientId: string;
    identityURL: string;
    marketoClientSecret: string;
    endPointURL: string;
    activeConnectionID: string;
    connectionURL: string;
    connectionsData: {};
    connectionErrors: string;
    connectionErrorDetail: string;
    connectionNameType: Array<any>;
    errorUniqueConnectionName: string;
    connectorTitle: string;
    modalDialogClass: string;
    baseLocationhRef: string;
    constructor(connectionService: ConnectionsService, salesforceoAuthService: SalesforceoAuthService, marketooAuthService: MarketooAuthService, _window: WindowRef, _router: Router, _activatedRoute: ActivatedRoute);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    modelChange(fieldName: any, event: any): void;
    closeAddNewConnection(): void;
    loginToOAuth(connectionCategory: string): void;
    salesforceoAuthFlow(): void;
    marketooAuthFlow(): void;
    getClassNameByConnectionType(connectionType: any): string;
    isInputTypeText(inputType: any): boolean;
    isInputTypeList(inputType: any): boolean;
    getInputValueFromConnections(fieldName: any): string;
    isOptional(isFieldRequired: any): string;
    getConnectorIconSrc(category: any): string;
}
