apiVersion: v1
kind: Pod
metadata:
  name: mtls-volume
spec:
  containers:
    - name: mtls-volume-container
      image: restserviceclientapp:1.1.2
      imagePullPolicy: Never
      env:
        - name: FLOGO_APP_PROPS_ENV
          value: auto
      volumeMounts:
        - name: server-secret-volume
          mountPath: /etc/server-secret-volume
          readOnly: true
        - name: client-secret-volume
          mountPath: /etc/client-secret-volume
          readOnly: true
  volumes:
    - name: server-secret-volume
      secret:
        secretName: server-secret
    - name: client-secret-volume
      secret:
        secretName: client-secret
